### ISSUE TITLE
Too many depenencies

### ISSUE THREAD

**Issue by Pnum** [cyChop/pixel2svg-fork#1]
There are so many dependencies.  Is it possible for you to make a standalone solution?   Otherwise, I have to download dependencies which need a dependency, ensure things are in proper paths and so on.  I'm using Mac a standalone would be great.  Thanks.  Also willing to pay if it's too much trouble time wise.

**Comment by cyChop** [comment]
Hi! This is a fork from somebody else's work, I chose to keep as close to the original as possible.

I've not used it in a while, but I remember no need to install anything. Did you do the `python setup.py install` as instructed in the README?

**Comment by Pnum** [comment]
Yes.  And PIL requires some dependencies.  svgwrite requires pip which requires proper paths to use.

**Comment by AntumDeluge** [comment]
It may be possible to create standalone executables with [cx_freeze](https://anthony-tuininga.github.io/cx_Freeze/). My Mac isn't working at the moment, so I can't create for that platform.

**Edit:** Oh! [py2app](https://pypi.org/project/py2app/) is specifically for making standalone OS X apps from Python scripts.

**Comment by aoloe** [comment]
i've created a version that works with python 3:

https://gitlab.com/a.l.e/pixel2svg

you can then install your dependencies with pip and put them in a venv.

**Comment by cyChop** [comment]
That's awesome! I'll add a note to the README and redirecting to your project.

Would you be OK if I also copied your adaptations into this project, so as to keep a historical view and have it up to date?

**Comment by aoloe** [comment]
hi

of course, you're welcome to get back the changes!

btw, my version of the script does work (i could create the svg i needed) but i did not check all the other options (i did run it without any options)

if you want, i can also do a pull request...

**Comment by cyChop** [comment]
Oh yes please, a pull request would be most welcome. It'd show that you were the one to do the work, not me. :)
